(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opACC0 = 0
let opACC1 = 1
let opACC2 = 2
let opACC3 = 3
let opACC4 = 4
let opACC5 = 5
let opACC6 = 6
let opACC7 = 7
let opACC = 8
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opPUSH = 9
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opPUSHACC0 = 10
let opPUSHACC1 = 11
let opPUSHACC2 = 12
let opPUSHACC3 = 13
let opPUSHACC4 = 14
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opPUSHACC5 = 15
let opPUSHACC6 = 16
let opPUSHACC7 = 17
let opPUSHACC = 18
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opPOP = 19
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opENVACC1 = 20
let opENVACC2 = 21
let opENVACC3 = 22
let opENVACC4 = 23
let opENVACC = 24
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opPUSHENVACC1 = 25
let opPUSHENVACC2 = 26
let opPUSHENVACC3 = 27
let opPUSHENVACC4 = 28
let opPUSHENVACC = 29
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opPUSH_RETADDR = 30
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opAPPLY = 31
let opAPPLY1 = 32
let opAPPLY2 = 33
let opAPPLY3 = 34
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opAPPTERM = 35
let opAPPTERM1 = 36
let opAPPTERM2 = 37
let opAPPTERM3 = 38
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opRETURN = 39
let opRESTART = 40
let opGRAB = 41
let opGRABREC = 42
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opCLOSURE = 43
let opCLOSUREREC = 44
let opCLOSURECOFIX = 45
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opOFFSETCLOSUREM2 = 46
let opOFFSETCLOSURE0 = 47
let opOFFSETCLOSURE2 = 48
let opOFFSETCLOSURE = 49
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opPUSHOFFSETCLOSUREM2 = 50
let opPUSHOFFSETCLOSURE0 = 51
let opPUSHOFFSETCLOSURE2 = 52
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opPUSHOFFSETCLOSURE = 53
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opGETGLOBAL = 54
let opPUSHGETGLOBAL = 55
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opMAKEBLOCK = 56
let opMAKEBLOCK1 = 57
let opMAKEBLOCK2 = 58
let opMAKEBLOCK3 = 59
let opMAKEBLOCK4 = 60
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opSWITCH = 61
let opPUSHFIELDS = 62
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opGETFIELD0 = 63
let opGETFIELD1 = 64
let opGETFIELD = 65
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opSETFIELD0 = 66
let opSETFIELD1 = 67
let opSETFIELD = 68
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opPROJ = 69
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opENSURESTACKCAPACITY = 70
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opCONST0 = 71
let opCONST1 = 72
let opCONST2 = 73
let opCONST3 = 74
let opCONSTINT = 75
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opPUSHCONST0 = 76
let opPUSHCONST1 = 77
let opPUSHCONST2 = 78
let opPUSHCONST3 = 79
let opPUSHCONSTINT = 80
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opACCUMULATE = 81
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opMAKESWITCHBLOCK = 82
let opMAKEACCU = 83
let opMAKEPROD = 84
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opBRANCH = 85
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opADDINT31 = 86
let opADDCINT31 = 87
let opADDCARRYCINT31 = 88
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opSUBINT31 = 89
let opSUBCINT31 = 90
let opSUBCARRYCINT31 = 91
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opMULCINT31 = 92
let opMULINT31 = 93
let opDIV21INT31 = 94
let opDIVINT31 = 95
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opADDMULDIVINT31 = 96
let opCOMPAREINT31 = 97
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opHEAD0INT31 = 98
let opTAIL0INT31 = 99
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opISCONST = 100
let opARECONST = 101
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opCOMPINT31 = 102
let opDECOMPINT31 = 103
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opORINT31 = 104
let opANDINT31 = 105
let opXORINT31 = 106
(* THIS FILE IS GENERATED. DON'T EDIT. *)

let opSTOP = 107
