// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';


function hash(param) {
  switch (param) {
    case 0 : 
        return 1;
    case 1 : 
        return 2;
    case 2 : 
        return 3;
    case 3 : 
        return 4;
    case 4 : 
        return 5;
    case 5 : 
        return 6;
    case 6 : 
        return 7;
    case 7 : 
        return 10;
    case 8 : 
        return 11;
    case 9 : 
        return 12;
    case 10 : 
        return 13;
    case 11 : 
        return 14;
    case 12 : 
        return 15;
    case 13 : 
        return 16;
    case 14 : 
        return 17;
    case 15 : 
        return 18;
    case 16 : 
        return 19;
    case 17 : 
        return 20;
    case 18 : 
        return 21;
    case 19 : 
        return 22;
    case 20 : 
        return 23;
    case 21 : 
        return 24;
    
  }
}

function to_string(param) {
  switch (param) {
    case 0 : 
        return "head0";
    case 1 : 
        return "tail0";
    case 2 : 
        return "add";
    case 3 : 
        return "sub";
    case 4 : 
        return "mul";
    case 5 : 
        return "div";
    case 6 : 
        return "mod";
    case 7 : 
        return "l_and";
    case 8 : 
        return "l_or";
    case 9 : 
        return "l_xor";
    case 10 : 
        return "addc";
    case 11 : 
        return "subc";
    case 12 : 
        return "addcarryc";
    case 13 : 
        return "subcarryc";
    case 14 : 
        return "mulc";
    case 15 : 
        return "diveucl";
    case 16 : 
        return "div21";
    case 17 : 
        return "addmuldiv";
    case 18 : 
        return "eq";
    case 19 : 
        return "lt";
    case 20 : 
        return "le";
    case 21 : 
        return "compare";
    
  }
}

exports.hash = hash;
exports.to_string = to_string;
/* No side effect */
