// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var TypeClassError = Caml_exceptions.create("Typeclasses_errors-ReactTemplate.TypeClassError");

function not_a_class(env, c) {
  throw [
        TypeClassError,
        env,
        /* NotAClass */Block.__(0, [c])
      ];
}

function unbound_method(env, cid, id) {
  throw [
        TypeClassError,
        env,
        /* UnboundMethod */Block.__(1, [
            cid,
            id
          ])
      ];
}

function mismatched_ctx_inst(env, c, n, m) {
  throw [
        TypeClassError,
        env,
        /* MismatchedContextInstance */Block.__(2, [
            c,
            n,
            m
          ])
      ];
}

exports.TypeClassError = TypeClassError;
exports.not_a_class = not_a_class;
exports.unbound_method = unbound_method;
exports.mismatched_ctx_inst = mismatched_ctx_inst;
/* No side effect */
